// One canonical source (skills/diffmode/SKILL.md) → three companion outputs:
//   - skills/diffmode/AGENTS.md            (< 2 KB; cross-tool agent contract)
//   - skills/diffmode/.cursor/rules/diffmode.mdc  (Cursor MDC rule)
//   - skills/diffmode/llms.txt             (Anthropic llms.txt pointer file)
//
// Running this script twice on the same SKILL.md MUST produce identical files
// — the drift check in test/sync-companions.test.ts depends on it.
//
// Usage (from diffmode-cli/):
//   tsx scripts/sync-companions.ts            # writes into skills/diffmode/
//   tsx scripts/sync-companions.ts <dir>      # writes into <dir>/ (testing)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";

export const OUTPUT_BANNER =
  "<!-- DO NOT EDIT — generated by scripts/sync-companions.ts from SKILL.md -->";

const REPO_URL = "https://github.com/agentic-builders/diffmode-cli";
const APP_URL = "https://diffmode.app";
const BILLING_URL = "https://diffmode.app/app/billing";

export interface CompanionOutputs {
  agents: string;
  cursor: string;
  llms: string;
}

export function syncCompanions(_skillSource: string): CompanionOutputs {
  return {
    agents: renderAgents(),
    cursor: renderCursor(),
    llms: renderLlms(),
  };
}

function renderAgents(): string {
  // Designed under 2 KB. Captures: when-to-use, key commands, exit codes,
  // idempotency contract, billing redirect, founder-input pointer. Everything
  // else lives in references/ (loaded on demand by skill-capable agents).
  return [
    `# diffmode — agent contract`,
    ``,
    OUTPUT_BANNER,
    ``,
    `Agent-drivable CLI for the Diffmode growth pipeline.`,
    ``,
    `## When to use`,
    `- User asks for a growth plan, personas, focus group, or any task using \`diffmode\`.`,
    `- Verify: \`diffmode --version\` and \`diffmode whoami --json\` (exit 4 → \`diffmode login\`).`,
    ``,
    `## Default flow`,
    `1. \`diffmode limits --json\` — confirm credits (1 run / 5 idea-eval / 15 unlock).`,
    `2. \`diffmode run <product> --input founder.json --idempotency-key <uuid> --json\``,
    `3. \`diffmode jobs watch <job_id> --json --wait 4h\` (stderr = progress).`,
    `4. \`diffmode results <product> --json\` — manifest first; never dump full bundle.`,
    `5. \`diffmode results <product> --summary --json\` — keyFinding sections (~3 k tok).`,
    `6. \`diffmode unlock <product> --idempotency-key <uuid> --json\` (optional, 15 cr).`,
    ``,
    `## Contract`,
    `- \`--json\` on every call. Stdout = data; stderr = progress/errors.`,
    `- **Idempotency is yours.** Generate a UUIDv4 per submit; CLI does NOT auto-generate.`,
    `- **Founder input** is required for \`run\`, \`workflow\`, \`smoke-test\`. Use \`--input\` or`,
    `  \`--from-url\`. \`unlock\` reuses the prior free-tier's input.`,
    `- \`idea-eval\` takes a JSON array (not strings) — see \`references/idea-input-schema.md\`.`,
    `- **Billing is browser-only.** On exit 8, redirect user to ${BILLING_URL}.`,
    ``,
    `## Exit codes (spec §8)`,
    `\`0\` ok · \`1\` generic · \`2\` usage · \`3\` network · \`4\` auth ·`,
    `\`5\` conflict · \`6\` not-found · \`7\` rate-limited · \`8\` insufficient-credits ·`,
    `\`9\` server · \`10\` interrupted-resumable · \`130\` SIGINT.`,
    `Full recovery: \`references/error-codes.md\`.`,
    ``,
    `## See also`,
    `- ${REPO_URL}`,
    `- ${APP_URL}`,
    ``,
  ].join("\n");
}

function renderCursor(): string {
  // Cursor MDC files use YAML frontmatter (description / globs / alwaysApply).
  // `alwaysApply: false` + `description:` makes Cursor offer this rule on
  // demand when the user references diffmode. We deliberately omit `globs:` —
  // diffmode usage isn't tied to a file pattern in the user's repo.
  const body = [
    `# diffmode CLI`,
    ``,
    OUTPUT_BANNER,
    ``,
    `Use the \`diffmode\` CLI to operate the hosted growth-strategy API.`,
    ``,
    `## When to invoke`,
    `- User asks for a growth plan, personas, focus group, or names diffmode.`,
    `- Confirm: \`diffmode --version\` and \`diffmode whoami --json\`.`,
    ``,
    `## Default flow`,
    `1. \`diffmode limits --json\` — credits.`,
    `2. \`diffmode run <product> --input founder.json --idempotency-key <uuid> --json\``,
    `3. \`diffmode jobs watch <job_id> --json --wait 4h\``,
    `4. \`diffmode results <product> --json\` then \`--summary --json\`.`,
    `5. \`diffmode unlock <product>\` (optional, 15 cr).`,
    ``,
    `## Contract`,
    `- Always pass \`--json\`. Stdout = data; stderr = progress/errors.`,
    `- Generate your own UUIDv4 for \`--idempotency-key\` (CLI never auto-generates).`,
    `- \`--input founder.json\` required for \`run\`/\`workflow\`/\`smoke-test\`.`,
    `- On exit 8, redirect user to ${BILLING_URL}. No CLI top-up command exists.`,
    `- Exit codes: \`4\` auth · \`5\` conflict (job_id in stderr) · \`7\` rate-limited ·`,
    `  \`8\` insufficient-credits · \`10\` interrupted-resumable.`,
    ``,
    `## Reference`,
    `- ${REPO_URL}`,
    `- ${APP_URL}`,
    ``,
  ].join("\n");

  const frontmatter = [
    `---`,
    `description: Operate the diffmode CLI to generate growth plans, personas, and focus-group simulations against the hosted Diffmode API.`,
    `alwaysApply: false`,
    `---`,
  ].join("\n");

  return `${frontmatter}\n${body}`;
}

function renderLlms(): string {
  // Anthropic llms.txt convention: `# Title`, blockquote summary, then
  // markdown link sections. Pointer file only — actual content lives at the
  // GitHub repo and the marketing site.
  return [
    `# diffmode`,
    ``,
    OUTPUT_BANNER,
    ``,
    `> Agent-drivable CLI for the Diffmode growth pipeline. Generate growth plans,`,
    `> personas, and focus-group simulations against the hosted Diffmode API. PAT`,
    `> auth, JSON-on-non-TTY, durable jobs, browser-only billing.`,
    ``,
    `## Docs`,
    ``,
    `- [Repository](${REPO_URL}): source, README, exit codes, CHANGELOG.`,
    `- [SKILL.md](${REPO_URL}/blob/main/skills/diffmode/SKILL.md): canonical agent skill.`,
    `- [Commands reference](${REPO_URL}/blob/main/skills/diffmode/references/commands.md): endpoint, credit cost, flags, examples per command.`,
    `- [Exit codes](${REPO_URL}/blob/main/skills/diffmode/references/error-codes.md): exit-code contract + per-code recovery scripts.`,
    `- [Founder input schema](${REPO_URL}/blob/main/skills/diffmode/references/founder-input-schema.md): \`FounderDiagnostics\` shape for \`--input\`.`,
    `- [Idea-eval input schema](${REPO_URL}/blob/main/skills/diffmode/references/idea-input-schema.md): \`IdeaInput\` array for \`--ideas-file\`.`,
    ``,
    `## Optional`,
    ``,
    `- [Dashboard](${APP_URL}): mint PATs at \`/app/tokens\`, top up credits at \`/app/billing\`.`,
    ``,
  ].join("\n");
}

export interface CompanionPaths {
  agents: string;
  cursor: string;
  llms: string;
}

export function writeCompanions(outputDir: string): CompanionPaths {
  const skillPath = resolve(outputDir, "SKILL.md");
  if (!existsSync(skillPath)) {
    throw new Error(`SKILL.md not found at ${skillPath}`);
  }
  const skillSource = readFileSync(skillPath, "utf8");
  const outputs = syncCompanions(skillSource);

  const paths: CompanionPaths = {
    agents: join(outputDir, "AGENTS.md"),
    cursor: join(outputDir, ".cursor", "rules", "diffmode.mdc"),
    llms: join(outputDir, "llms.txt"),
  };

  for (const target of Object.values(paths)) {
    mkdirSync(dirname(target), { recursive: true });
  }

  writeFileSync(paths.agents, outputs.agents, "utf8");
  writeFileSync(paths.cursor, outputs.cursor, "utf8");
  writeFileSync(paths.llms, outputs.llms, "utf8");

  return paths;
}

function isCliEntry(): boolean {
  // tsx/node sets process.argv[1] to the script path. Compare against
  // __filename + a .ts/.js sibling to support both `tsx scripts/foo.ts`
  // and the bundled CJS form.
  const entry = process.argv[1];
  if (!entry) return false;
  return entry.endsWith("sync-companions.ts") || entry.endsWith("sync-companions.js");
}

if (isCliEntry()) {
  const argDir = process.argv[2];
  const targetDir = argDir
    ? resolve(process.cwd(), argDir)
    : resolve(__dirname, "..", "skills", "diffmode");
  const written = writeCompanions(targetDir);
  console.error(`Wrote: ${written.agents}`);
  console.error(`Wrote: ${written.cursor}`);
  console.error(`Wrote: ${written.llms}`);
}
